Document: sentencepiece
Title: Debian sentencepiece Manual
Author: <insert document author here>
Abstract: This manual describes what sentencepiece is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/sentencepiece/sentencepiece.sgml.gz

Format: postscript
Files: /usr/share/doc/sentencepiece/sentencepiece.ps.gz

Format: text
Files: /usr/share/doc/sentencepiece/sentencepiece.text.gz

Format: HTML
Index: /usr/share/doc/sentencepiece/html/index.html
Files: /usr/share/doc/sentencepiece/html/*.html
